### ISSUE TITLE
Error when uploading a file

### ISSUE THREAD

**Issue by asad214** [jdalrymple/gitbeaker#1046]
**Description**

Uploading a file fails with a TypeError

```
TypeError: source.on is not a function
    at Function.DelayedStream.create (C:\Users\...\Documents\backend\node_modules\delayed-stream\lib\delayed_stream.js:33:10)
    at FormData.CombinedStream.append (C:\Users\...\Documents\backend\node_modules\combined-stream\lib\combined_stream.js:45:37)
    at FormData.append (C:\Users\...\Documents\backend\node_modules\form-data\lib\form_data.js:74:3)
    at C:\Users\...\Documents\backend\node_modules\@gitbeaker\core\dist\index.js:1:3979
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\...\Documents\backend\node_modules\@gitbeaker\core\dist\index.js:1:3890)
    at C:\Users\...\Documents\backend\node_modules\@gitbeaker\core\dist\index.js:1:3094
    at Object.next (C:\Users\...\Documents\backend\node_modules\@gitbeaker\core\dist\index.js:1:3199)
    at C:\Users\...\Documents\backend\node_modules\@gitbeaker\core\dist\index.js:1:2136
    at new Promise (<anonymous>)
```

**Steps to reproduce**

```
const { Gitlab } = require('@gitbeaker/node');

const api = new Gitlab({
  host: url,
  token: token,
});

api.Projects.upload(1877, 'Testing file upload', {
  filename: 'test.txt'
}).then( res => {
  console.log(res)
}).catch( error => {
  console.log(error);
})
```

**Comment by jdalrymple** [comment]
This may be fixed with #1056, give it a look once the release is deployed!

**Comment by asad214** [comment]
That fix worked! Thank you 👍

**Comment by toppermitz** [comment]
Same error for me on current realease

**Comment by jdalrymple** [comment]
Can you provide a little more information? I tested it just now and received a correct response.
