### ISSUE TITLE
`npm run-script build` fails (`npm install` does **not** install the `devDependencies`)

### ISSUE THREAD

**Issue by kiprasmel** [jdalrymple/gitbeaker#1105]
**Description**

Going through the installation steps, `npm install` does not install the dev dependencies, and then the build script fails. This is because, I assume, the `package-lock.json` (or `yarn.lock`) file is not tracked inside the repository (which it almost always should be). Yarn would still work I think, but npm somehow fails.

I understood this because once there was an error that a package is missing, I installed it explicitly, thus it got added into the package-lock.json and the error went away. Then another package was missing, and the same fix worked.

**Steps to reproduce**

```sh
t1434@t1434mac.local gitbeaker (master *% u=)]$ npm install
audited 1535 packages in 6.075s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install  7.58s user 0.80s system 113% cpu 7.389 total
[t1434@t1434mac.local gitbeaker (master *% u=)]$ npm run-script build

> gitbeaker@ build /Users/t1434/oss/refined-gitlab/gitbeaker
> lerna run build

lerna notice cli v3.22.1
lerna info Executing command in 5 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@gitbeaker/requester-utils'
lerna ERR! yarn run build stdout:
yarn run v1.22.4
$ tsc && rollup -c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
[!] Error: Cannot find module 'rollup-plugin-typescript2'
Require stack:
- /Users/t1434/oss/refined-gitlab/gitbeaker/packages/gitbeaker-requester-utils/rollup.config.js
- /Users/t1434/.local/share/yarn/global/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/t1434/.local/share/yarn/global/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-typescript2'
Require stack:
- /Users/t1434/oss/refined-gitlab/gitbeaker/packages/gitbeaker-requester-utils/rollup.config.js
- /Users/t1434/.local/share/yarn/global/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/t1434/.local/share/yarn/global/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/t1434/oss/refined-gitlab/gitbeaker/packages/gitbeaker-requester-utils/rollup.config.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.require.extensions.<computed> [as .js] (/Users/t1434/.local/share/yarn/global/node_modules/rollup/dist/shared/loadConfigFile.js:520:20)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@gitbeaker/requester-utils'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gitbeaker@ build: `lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gitbeaker@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/t1434/.npm/_logs/2020-08-23T13_42_57_606Z-debug.log
npm run-script build  9.50s user 0.66s system 157% cpu 6.446 total
[t1434@t1434mac.local gitbeaker (master *% u=)]$ 
[t1434@t1434mac.local gitbeaker]$ echo $NODE_ENV

[t1434@t1434mac.local gitbeaker (master *% u=)]$ echo $CI

```

**Expected behaviour**

Builds successfully

**Actual behaviour**

Fails

**Possible fixes**

Track the `package-lock.json` file in git.

**Quick work-around to install all devDependencies**

```sh
npm i -D `node -e 'console.log(Object.keys(require("./package.json").devDependencies).join(" "))'`
```

Edit: some dependencies were also not defined in the package.json, so you additionally need to install them:

```sh
npm i -D <TBD>
```

Edit 2: Wait - it seems that the problem is is that `npm install` does not install the dependencies of all packages, but rather only the root ones - help?

Edit 3: Wait - you're obviously using yarn here. Huh - that's confusing - the installation docs need to be updated.

Edit 4: Created a fix for the docs: https://github.com/jdalrymple/gitbeaker/pull/1107 (though there're some different issues now)

**Comment by jdalrymple** [comment]
Sorry for causing all the confusion :joy:
