### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by muuvmuuv** [jdalrymple/gitbeaker#1146]
**Description**

I am trying to create a merge request which unexpectly fails. The GitLab API is accesible and I double checked by post curl the same request.

```js
const services = new ProjectsBundle({
    host: 'xxxxx',
    token: process.env.GITLAB_ACCESS_TOKEN,
  })
    await services.MergeRequests.create({
      projectId: project,
      sourceBranch: 'develop',
      targetBranch: 'master',
      title: `New release v${currentVersion}`,
      options: {
        description: changelog,
        removeSourceBranch: false,
        labels: 'release',
        showExpanded: true,
      },
    })
```

Works:

```shell
curl --request POST \
  --url 'xxxx/api/v4/projects/xx/merge_requests?access_token=xxxxxx' \
  --header 'content-type: application/json' \
  --data '{
	"id": xx,
	"source_branch": "develop",
	"target_branch": "master",
	"title": "test"
}'
```

```
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (///node_modules/@gitbeaker/node/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1600090164284,
    socket: 1600090164287,
    lookup: 1600090164290,
    connect: 1600090164293,
    secureConnect: 1600090164300,
    upload: 1600090164300,
    response: 1600090164329,
    end: 1600090164332,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 3,
      tcp: 3,
      tls: 7,
      request: 0,
      firstByte: 29,
      download: 3,
      total: 48
    }
  },
  description: undefined
}
```

**Steps to reproduce**

Try to run the above JS maybe. Idk but this is a internal GitLab so pretty impossible.

**Possible fixes**

I would like to dig deeper into this but cannot see any `debug` or `verbose` option. Debugging through the sourcecode is impossible due to #1114

**Comment by jdalrymple** [comment]
This will be fixed soon. Im exposing the source in #1112 PR

**Comment by 540692039** [comment]
the same problem, i create an existed branch, but i can't get error message

though in devtools -> network i can find it, but in my

**Comment by stereonom** [comment]
when I create a MR ike this it works!
```js
return gitlab.MergeRequests.create(
return gitlab.MergeRequests.create(
	123,
	'develop',
	'master',
	'super release',
	{
		assigneeIid: 13,
		description: 'Release all the things',
		removeSourceBranch: false,
		labels: 'release'
	}
);
```

Just don't wrap  the options in an object  ¯\_(ツ)_/¯

**Comment by jdalrymple** [comment]
The function doesnt take in an object to begin with, which would be the source of your problem hehe as you found out ^ there
