### ISSUE TITLE
FormData__namespace is not a constructor when invoking Triggers.pipeline

### ISSUE THREAD

**Issue by Banditnic** [jdalrymple/gitbeaker#1294]
Hello,

Invoking Triggers.pipeline causes a TypeError on line 155 of @gitbreaker/core/dist/index.js

TypeError: FormData__namespace is not a constructor
    at appendFormFromObject (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:155:16)
    at Object.<anonymous> (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:240:37)
    at step (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:116:23)
    at Object.next (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:97:53)
    at c:\myproject\node_modules\@gitbeaker\core\dist\index.js:90:71
    at new Promise (<anonymous>)
    at __awaiter (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:86:12)
    at Object.post (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:235:12)
    at Triggers.pipeline (c:\myproject\node_modules\@gitbeaker\core\dist\index.js:2599:30)
    at Object.startGitlabPipeline [as start] (c:\myproject\myfolder\anotherfolder\mymodule.js:19:39)

My invocation in screenshot below

![image](https://user-images.githubusercontent.com/71794156/97922303-3d58e500-1d2a-11eb-9d80-8b80f61fe4af.png)

**Comment by Banditnic** [comment]
Setting isForm to false on line 2599 in @gitbreaker/core/dist/index.js seems to resolve the issue, I can start pipelines, but I'm guessing this isn't the proper way to fix this, haha. Any help much appreciated. Thank you!

**Comment by jdalrymple** [comment]
Ill give it a look!

**Comment by jdalrymple** [comment]
I see this occasionally when its building in the tests, but it isnt consistent. Is it still throwing the error in the latest release?

**Comment by creativeux** [comment]
I'm also seeing this issue with a simple `instance.Triggers.pipeline(projectId, branchRef, token)` on 25.4.0.

**Comment by jdalrymple** [comment]
Ill dig into it when i get a moment!

**Comment by jdalrymple** [comment]
Its related to form-data, its been a problem I've only ever been able to temporarily fix 

#1112 

https://github.com/form-data/form-data/issues/470

I can try taking another stab at it again at somepoint soon

**Comment by jdalrymple** [comment]
Finally think i figured it out. It looks like it may be due to circular references, which causes the tests to bomb even though the code itself is fine. So while i might change the code to fix this error about the form data, the tests would error out stopping me from deploying. 

I'm working on reorganizing things to fix this error. Might be a lil bit though since things are pretty connected haha

**Comment by jdalrymple** [comment]
Just deployed a canary version with this fix. Give it a look! @creativeux  @Shakes03  @Banditnic

**Comment by creativeux** [comment]
@jdalrymple I can confirm that the canary release you published works for my application! Thanks for the quick turnaround!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`27.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/27.0.0) :rocket:
