### ISSUE TITLE
Missing dist files in 29.3 release

### ISSUE THREAD

**Issue by tschaub** [jdalrymple/gitbeaker#1861]
It looks like the `dist` files are missing from releases after 29.2.4.

**Steps to reproduce**

```
npm install @gitbeaker/node@29.3
ls node_modules/@gitbeaker/node
# LICENSE.md   README.md    package.json
```

**Expected behaviour**
```
npm install @gitbeaker/node@29.2
ls node_modules/@gitbeaker/node
# LICENSE.md   README.md    dist         package.json
```

**Actual behaviour**

Since `package.json` points to `dist` files (in `main` etc.), it is not possible to import/require the package.
```
node:internal/modules/cjs/loader:356
      throw err;
      ^

Error: Cannot find module '/path/to/project/node_modules/@gitbeaker/node/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:348:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:561:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/path/to/project/test.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/path/to/project/node_modules/@gitbeaker/node/package.json',
  requestPath: '@gitbeaker/node'
}
``` 

**Possible fixes**

Maybe something related to #1851.

**Comment by jdalrymple** [comment]
Wait what haha. How does that happen :thinking:

**Comment by jdalrymple** [comment]
I think i found it!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`30.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/30.1.0) :rocket:

**Comment by tschaub** [comment]
Looks like that might have been part of it, but I'm still not seeing `dist` in the 30.1.0 release(s).

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`30.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/30.2.0) :rocket:

**Comment by tschaub** [comment]
30.2.0 looks good.  Thanks, @jdalrymple

**Comment by jdalrymple** [comment]
Thanks for the catch! @tschaub

**Comment by pavel-kurnosov** [comment]
@jdalrymple looks like now it is similar problem with techdocs/cli.. I am getting now with the latest version 
```
.nvm/versions/node/v14.17.3/lib/node_modules/@techdocs/cli/dist/index.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/.nvm/versions/node/v14.17.3/lib/node_modules/@techdocs/cli/bin/techdocs-cli:25:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '.nvm/versions/node/v14.17.3/lib/node_modules/@techdocs/cli/package.json',
  requestPath: '..'
}
```

**Comment by jdalrymple** [comment]
This is really odd, the pkg.json points to the correct location :thinking:

**Comment by jdalrymple** [comment]
Seems to only of affected the cli release too
