### ISSUE TITLE
[ProjectImportExport] ECONNRESET on import project into GitLab.com

### ISSUE THREAD

**Issue by arnaud-dumont-vcgs** [jdalrymple/gitbeaker#2055]
**Description**

First of all: thanks for this great library!

I'm attempting to export and then import a GitLab project into GitLab.com.

I followed the discussion and solution proposed in https://github.com/jdalrymple/gitbeaker/issues/1139.<br>
I first tested it against our own private on-prem instance of GitLab (of version `GitLab Community Edition 13.12.10`). And this worked, for both the project export and then the import into it. 

But then I tried the same code against our account in GitLab.com (of version `GitLab Enterprise Edition 14.3.0-pre 3be814bb1f3`). And this time, the project export worked, but I consistently got the following error on `ProjectImportExport.import()`, after a few seconds:
```
error: socket hang up
error: {"name":"RequestError","code":"ECONNRESET","timings":{"start":1630632520155,"socket":1630632520155,"lookup":1630632520155,"connect":1630632520172,"secureConnect":1630632520197,"error":1630632535184,"phases":{"wait":0,"dns":0,"tcp":17,"tls":25,"total":15029}},"level":"error"} {"timestamp":"2021-09-03T01:28:55.189Z"}
```

Here are the dependencies I'm using:
```json
"@gitbeaker/core": "^33.0.1",
"@gitbeaker/node": "^33.0.1",
```

Here's the pseudo-code I used:
```js
// Schedule export
const fromProject = new Gitlab({ ...creds });
fromProject.ProjectImportExport.schedule(fromProjectIdentifier);

// Download export
const projectExport = await fromProject.ProjectImportExport.download(fromProjectIdentifier);
const tempFilePath = `./project_${fromProjectDetails.projectIdentifier}.tar.gz`;
fs.writeFileSync(tempFilePath, projectExport as any);

// Schedule import
const toProject = new Gitlab({ ...creds });
await toProject.ProjectImportExport.import(
  fs.createReadStream(tempFilePath) as any,
  projectName,
  {
    overwrite,
    namespace,
  }
);
```

I also tried to use the temp file that was imported successfully in own private on-prem instance of GitLab, and import it in GitLab.com, but it didn't work either.

I also tried to configure the `requestTimeout` parameter on the `GitLab()` instance, but it didn't work either.

It's not due to my connection or access token to GitLab.com, as the communication to export the project from GitLab.com did work.

Less important, but I also saw something else: if I omit the `namespace` option, the default behaviour is that it should import the project in my own namespace, but I rather get this error:
```
Cannot read property 'name' of undefined
```
Not sure if it's a related error or not.

**Steps to reproduce**

- Export project as `.tar.gz` file, using `ProjectImportExport.download()`
- Try to import that project into GitLab.com, using `ProjectImportExport.import()`

**Expected behaviour**

Import in GitLab.com should be successful, as per successful import on our own private on-prem instance of GitLab.

**Actual behaviour**

`ECONNRESET` received from GitLab.com on all attempts.

**Possible fixes**

Not sure what this is due to? Can someone else reproduce?

Or is it due to the difference in versions between GitLab.com (more recent Enterprise Edition) and our own private on-prem instance of GitLab (older Community Edition)?

Thanks in advance!

**Comment by jdalrymple** [comment]
Weird, ive tested this with gitlab.com without an issue. Ill give it a look and follow up!

**Comment by arnaud-dumont-vcgs** [comment]
Thanks for looking into this.

I've done a few more tests myself, and this is what I found:

## Using `curl`
If I use `curl` to import the project, it works, with or without specifying the `namespace`:
```bash
$ curl -X POST -H 'PRIVATE-TOKEN: <token>' --form "path=testImport" --form "file=@./project_28933575.tar.gz" https://gitlab.com/api/v4/projects/import

{"id":29475596,"description":null,"name":"testImport","name_with_namespace":"<my own namespace> / testImport","path":"testImport","path_with_namespace":"<my own namespace>/testImport","created_at":"2021-09-09T05:00:22.855Z","import_status":"scheduled","correlation_id":"01FF4EV8SK953S721GCY3JA1HT","failed_relations":[],"import_error":null}


$ curl -X POST -H 'PRIVATE-TOKEN: <token>' --form "path=testImport" --form "file=@./project_28933575.tar.gz" --form "namespace=<my company namespace>" https://gitlab.com/api/v4/projects/import

{"id":29475646,"description":null,"name":"testImport","name_with_namespace":"<my company namespace> / testImport","path":"testImport","path_with_namespace":"<my company namespace>/testImport","created_at":"2021-09-09T05:06:11.604Z","import_status":"scheduled","correlation_id":"01FF4F5XJ473R2K4SXPCQCE5ZG","failed_relations":[],"import_error":null}
```

## `gitbeaker` without namespace
If I use `gitbeaker` without specifying the `namespace`:
```js
toProject.ProjectImportExport.import(
  fs.createReadStream(exportedProjectFilePath) as any,
  projectName,
  { overwrite: "false"},
);
```

It fails with:
```
error: Cannot read property 'name' of undefined

error: TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/form-data/lib/form_data.js:227:40)
    at FormData._multiPartHeader (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/form-data/lib/form_data.js:178:33)
    at FormData.append (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/form-data/lib/form_data.js:71:21)
    at /Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:140:18
    at Array.forEach (<anonymous>)
    at appendFormFromObject (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:135:28)
    at Object.<anonymous> (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:220:41)
    at step (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:102:23)
    at Object.next (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:83:53)
    at /Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@gitbeaker/core/dist/index.js:76:71
```

## `gitbeaker` with namespace
If I use `gitbeaker` with specifying the `namespace`:
```js
toProject.ProjectImportExport.import(
  fs.createReadStream(exportedProjectFilePath) as any,
  projectName,
  {
    overwrite: "false",
    "namespace":"<my company namespace>"
  },
);
```

It fails with:
```
error: socket hang up

error: RequestError: socket hang up
    at ClientRequest.<anonymous> (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/Users/arnaud.dumont/Dev/Projects/Local_infra/gitlab-etl-processes/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

error: undefined {"name":"RequestError","code":"ECONNRESET","timings":{"start":1631164233298,"socket":1631164233298,"lookup":1631164233298,"connect":1631164233309,"secureConnect":1631164233328,"error":1631164248324,"phases":{"wait":0,"dns":0,"tcp":11,"tls":19,"total":15026}},"timestamp":"2021-09-09T05:10:48.327Z"}
```

I tried updating the client timeout in the `new Gitlab()`, but that didn't work either.<br>
I'm using a `personal access token` with scope `api`.<br>
Note that with an invalid namespace with `curl`, I get a `404 Namespace Not Found`, but with `gitbeaker`, I still get the `ECONNRESET`.

So I'm not too sure what else to try...

**Comment by jdalrymple** [comment]
So a few suggestions here. The first argument isnt a stream, but a blob, so id save the content of your file to a var and pass that as the first argument. The rest of the code seems fine though. I think thats the main issue causing the error.


```ts
toProject.ProjectImportExport.import(
  fs.createReadStream(exportedProjectFilePath) as any,
  projectName,
  { overwrite: "false"},
);
```
