### ISSUE TITLE
500 Internal Server Error on MergeRequests.all()

### ISSUE THREAD

**Issue by mbrammer** [jdalrymple/gitbeaker#3296]
**Description**

- Node.js version: v18.16.0
- Gitbeaker version: 38.9.0
- Gitbeaker release (cli, node, browser, core, requester-utils): @gitbeaker/rest

I am seeing 500 errors from time to time (not always) when calling the `MergeRequests.all()` like this:
```
MergeRequests.all({
  groupId: [...],
  scope: 'all',
  state: 'opened',
  wip: 'no',
})
```
The params (including groupId) are always the same.  

Maybe this is an Gitlab API issue itself, but I wanted to raise it here first, just in case ;)  

This is the error:
```
[...]/node_modules/@gitbeaker/rest/dist/index.js:81
  throw new Error(response.statusText, {
        ^

Error: Internal Server Error
    at throwFailedRequestError ([...]/node_modules/@gitbeaker/rest/dist/index.js:81:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultRequestHandler ([...]/node_modules/@gitbeaker/rest/dist/index.js:102:7)
    at async [...]/node_modules/@gitbeaker/core/dist/index.js:104:22
    at async [...]/src/shared/service/merge-request.service.js:452:35 {
  [cause]: {
    description: '"500 Internal Server Error"',
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: {
        aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 500,
        timingInfo: {
          startTime: 32580772.945480347,
          redirectStartTime: 0,
          redirectEndTime: 0,
          postRedirectStartTime: 32580772.945480347,
          finalServiceWorkerStartTime: 0,
          finalNetworkResponseStartTime: 0,
          finalNetworkRequestStartTime: 0,
          endTime: 32641684.54547119,
          encodedBodySize: 0,
          decodedBodySize: 0,
          finalConnectionTimingInfo: null
        },
        cacheState: '',
        statusText: 'Internal Server Error',
        headersList: HeadersList {
          cookies: [
            '_cfuvid=a45HjHzaQbUiwJ5EYhDPRnXRmrrqNiLB8W4NC0RlHLU-1686035103174-0-604800000; path=/; domain=.gitlab.com; HttpOnly; Secure; SameSite=None'
          ],
          [Symbol(headers map)]: Map(26) {
            'date' => [Object],
            'content-type' => [Object],
            'content-length' => [Object],
            'connection' => [Object],
            'cache-control' => [Object],
            'content-security-policy' => [Object],
            'vary' => [Object],
            'x-gitlab-meta' => [Object],
            'x-request-id' => [Object],
            'x-runtime' => [Object],
            'strict-transport-security' => [Object],
            'referrer-policy' => [Object],
            'ratelimit-observed' => [Object],
            'ratelimit-remaining' => [Object],
            'ratelimit-reset' => [Object],
            'ratelimit-resettime' => [Object],
            'ratelimit-limit' => [Object],
            'gitlab-lb' => [Object],
            'gitlab-sv' => [Object],
            'cf-cache-status' => [Object],
            'report-to' => [Object],
            'nel' => [Object],
            'x-content-type-options' => [Object],
            'set-cookie' => [Object],
            'server' => [Object],
            'cf-ray' => [Object]
          },
          [Symbol(headers map sorted)]: null
        },
        urlList: [
          URL {
            [Symbol(context)]: [URLContext],
            [Symbol(query)]: [URLSearchParams]
          }
        ],
        body: {
          stream: ReadableStream {
            [Symbol(kType)]: 'ReadableStream',
            [Symbol(kState)]: [Object],
            [Symbol(nodejs.webstream.isClosedPromise)]: [Object],
            [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function: bound error]
          }
        }
      },
      [Symbol(headers)]: Headers {
        [Symbol(headers list)]: HeadersList {
          cookies: [
            '_cfuvid=a45HjHzaQbUiwJ5EYhDPRnXRmrrqNiLB8W4NC0RlHLU-1686035103174-0-604800000; path=/; domain=.gitlab.com; HttpOnly; Secure; SameSite=None'
          ],
          [Symbol(headers map)]: Map(26) {
            'date' => [Object],
            'content-type' => [Object],
            'content-length' => [Object],
            'connection' => [Object],
            'cache-control' => [Object],
            'content-security-policy' => [Object],
            'vary' => [Object],
            'x-gitlab-meta' => [Object],
            'x-request-id' => [Object],
            'x-runtime' => [Object],
            'strict-transport-security' => [Object],
            'referrer-policy' => [Object],
            'ratelimit-observed' => [Object],
            'ratelimit-remaining' => [Object],
            'ratelimit-reset' => [Object],
            'ratelimit-resettime' => [Object],
            'ratelimit-limit' => [Object],
            'gitlab-lb' => [Object],
            'gitlab-sv' => [Object],
            'cf-cache-status' => [Object],
            'report-to' => [Object],
            'nel' => [Object],
            'x-content-type-options' => [Object],
            'set-cookie' => [Object],
            'server' => [Object],
            'cf-ray' => [Object]
          },
          [Symbol(headers map sorted)]: null
        },
        [Symbol(guard)]: 'immutable',
        [Symbol(realm)]: null
      }
    }
  }
}
```

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I think this is due to the # of requests. By default, it tries to get ALL the items, automatically handling pagination in the background. While this is helpful, if their is a vast amount of data, it can timeout OR run for a very long period without feedback. If you add `maxPages: some number` to your query it should be fine. Also note, groupId is a number not an array.

**Comment by jdalrymple** [comment]
Actually no, hmm, when i perform this request, i get a timeout (408) but you got  a 500. Im not sure. Could you create a sample project so i could try to replicate it?

**Comment by mbrammer** [comment]
Okay, so I had the issue again a few minutes ago and I was diving a bit deeper. I figured out it comes from another child call inside my method. Not sure if it was the same method last time, but this time I got the 500 from the `Projects.show()`.
I am simply doing this:
```
let project: ProjectSchema;

try {
  project = await this.gitlab.Projects.show(...);
} catch (error) {
  console.log(error);
  return null;
}
```

And yes, I know that with the array/number. I just added `[...]` as placeholder ;)

**Comment by jdalrymple** [comment]
Hmm, so it isnt the method exactly.  Are you accessing gitlab.com or a custom instance?

**Comment by mbrammer** [comment]
I am accessing gitlab.com

**Comment by jdalrymple** [comment]
I have no idea, could you throw that snippet in a sample project so i can recreate the problem locally?

**Comment by mbrammer** [comment]
It's basically just the lines from my comment above. It's also just happening very rare.  
I actually think it's related to Gitlabs servers. Maybe when they are under heavy load or have some outage 🤷‍♂️ 
So maybe we can close this.

**Comment by jdalrymple** [comment]
If it keeps happening and you can recreate it in a standalone project (beyond those lines above), id love to see that code to see if its an error within the logic.  Hopefully it remains infrequent!
