### ISSUE TITLE
ReferenceError: FormData is not defined

### ISSUE THREAD

**Issue by tennox** [jdalrymple/gitbeaker#3587]
**Description**

- Node.js version: `v16.17.1`
- Gitbeaker release (cli, rest, core, requester-utils): `@gitbeaker/cli@40.0.3`
- OS & version: docker alpine, linux 6.6.30

```
bash-5.1# npm -g ls
/usr/local/lib
├── @babel/runtime@7.24.5
├── @gitbeaker/cli@40.0.3
└── semantic-release@23.1.1

bash-5.1# gitbeaker merge-requests create 123 stage tmp title
(node:84) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: FormData is not defined
    at defaultOptionsHandler (file:///usr/local/lib/node_modules/@gitbeaker/cli/node_modules/@gitbeaker/requester-utils/dist/index.mjs:37:25)
    at Object.requester.<computed> [as post] (file:///usr/local/lib/node_modules/@gitbeaker/cli/node_modules/@gitbeaker/requester-utils/dist/index.mjs:71:45)
    at file:///usr/local/lib/node_modules/@gitbeaker/cli/node_modules/@gitbeaker/core/dist/index.mjs:138:46
    at Object.create (file:///usr/local/lib/node_modules/@gitbeaker/cli/node_modules/@gitbeaker/core/dist/index.mjs:4041:32)
    at runAPIMethod (file:///usr/local/lib/node_modules/@gitbeaker/cli/dist/index.mjs:165:24)
    at TypeCommand.run [as _runHandler] (file:///usr/local/lib/node_modules/@gitbeaker/cli/dist/index.mjs:183:27)
    at /usr/local/lib/node_modules/@gitbeaker/cli/node_modules/sywac/types/command.js:131:19
    at async Promise.all (index 19)
    at async Promise.all (index 97)
```

**Steps to reproduce**

1. `docker run registry.gitlab.com/onezoomin/docker-allsync-cligitlab`
2. upgrade to latest gitbeaker: `npm i -g @gitbeaker/cli`
3. `export GITLAB_TOKEN=123`
4. `gitbeaker merge-requests create 123 main tmp title`

**Possible fixes**

Similar issue in axios (https://github.com/axios/axios/issues/5202) was about environment :thinking: 

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by tennox** [comment]
a base image & nodejs upgrade (v20 now) seems to have fixed the issue.
