### ISSUE TITLE
Support request - TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by DavidFaizulaev** [jdalrymple/gitbeaker#526]
I'm trying to use the API package and I get the following exception when trying to create a commit:

```
(node:11023) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at defaultRequest (/Users/david/Documents/gitlab/package-radar/node_modules/gitlab/dist/index.js:1:3491)
    at Object.<anonymous> (/Users/david/Documents/gitlab/package-radar/node_modules/gitlab/dist/index.js:1:4562)
    at /Users/david/Documents/gitlab/package-radar/node_modules/gitlab/dist/index.js:1:2503
```

I get the error when trying to create a commit:

```
function initGitlabApi() {
    const gitlabApi = new Gitlab({
        host: 'https://git.david.co',
        token: 'some_valid_token'
    });
    commitsApi = gitlabApi.Commits.requester;
}

async function createCommit(commitRequestBody) {
    const response = await commitsApi.post(commitRequestBody);
    return response;
}
```
The token I use & url are valid (I'm able to interact with gitlab API using regular nodejs 'request' module).

Please advise what am I doing wrong?

**Comment by casz** [comment]
You should not use the requester object directly...

You want to use the create method on Commits service: 
```javascript
const gitlabApi = new Gitlab({
  host: 'https://git.david.co',
  token: 'some_valid_token'
});

const readme = "# Hello World"

await gitlabApi.Commits.create('group/project', {
  branch: 'master',
  message: 'Hello World',
  actions: [
    {
      action: 'create',
      filePath: 'README.md',
      content: readme
    }
  ]
})
```
