### ISSUE TITLE
Got NOT FOUND when trying to add deploy key

### ISSUE THREAD

**Issue by hlwjia** [jdalrymple/gitbeaker#635]
I am trying to add deploy key to my repo.

```
const api = new GitlabAPI({token: GL_TOKEN})
api.DeployKeys.add({
    projectId: PROJECT_ID,
    title: 'some title',
    key: PUBLIC_KEY_STRING,
    canPush: false,
})
```

It returns `404 NOT FOUND` message.

```
HTTPError: Not Found
at fn (/PATH_OF_PROJECT/src/node_modules/ky/umd.js:279:12)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
Based on the `Not Found`, I can only assume it's `projectId` I got wrong. But I checked MANY MANY times to make sure the projectId is correct.

---

It works perfectly when I curl it as [official docs](https://docs.gitlab.com/ee/api/deploy_keys.html#add-deploy-key) says.

```
curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" --header "Content-Type: application/json" --data '{"title": "My deploy key", "key": "ssh-rsa AAAA...", "can_push": "true"}' "https://gitlab.com/api/v4/projects/{{PROJECT_ID}}/deploy_keys/"
```

---

What am I doing wrong?

**Comment by hlwjia** [comment]
Damn it!  Careless mistakes.

should be this:

```
api.DeployKeys.add(
  PROJECT_ID,
  {
    title: 'some title',
    key: PUBLIC_KEY_STRING,
    canPush: false,
  }
)
```
