### ISSUE TITLE
Missing required argument: mergerequest-i-id

### ISSUE THREAD

**Issue by hadrien-toma** [jdalrymple/gitbeaker#854]
**Description**

Can not reach to show a merge request.

- `--mergerequest-id` as parameter gives:

```sh
yarn run --silent gitbeaker merge-requests show --gl-token=MYTOKEN --project-id=MYPROJECTID --mergerequest-id=MYMERGEREQUESTID 
Usage: gitbeaker merge-requests show [--project-id] <project-id> [--mergerequest-i-id] <mergerequest-i-id> [options]

Required Options
  [--project-id] <project-id>                                                    [required] [string]
  [--mergerequest-i-id] <mergerequest-i-id>                                      [required] [string]

Base Options
  gb-token <value>            Your Gitlab Personal Token
                              [string]

  gb-oauth-token <value>      Your Gitlab OAuth Token
                              [string]

  gb-job-token <value>        Your Gitlab Job Token
                              [string]

  gb-host <value>             Your Gitlab API host (Defaults to https://www.gitlab.com)
                              [string]

  gb-version <value>          The targetted Gitlab API version (Defaults to 4)
                              [number]

  gb-sudo <value>             [Sudo](https://docs.gitlab.com/ee/api/#sudo) query parameter
                              [string]

  gb-camelize <value>         Camelizes all response body keys
                              [boolean]

  gb-request-timeout <value>  Timeout for API requests. Measured in ms
                              [number]

  gb-profile-token <value>    [Requests Profile
                              s
                              Token](https://docs.gitlab.com/ee/administration/monitoring/performan
                              ce/request_profiling.html)
                              [string]

  gb-profile-mode <value>     [Requests Profile
                              s
                              Token](https://docs.gitlab.com/ee/administration/monitoring/performan
                              ce/request_profiling.html)
                              [string]

Options:
  -v, --version      Show version number
                     [commands: version] [boolean]

  -h, --help         Show help
                     [commands: help] [boolean]

  -g, --global-args  Show global arguments currently set in the enviroment variables
                     [commands: global-args] [boolean]

Copyright 2019

Missing required argument: mergerequest-i-id
```

- `--mergerequest-id` as parameter gives:

```sh
yarn run --silent gitbeaker merge-requests show --gl-token=MYTOKEN --project-id=MYPROJECTID --mergerequest-i-id=MYMERGEREQUESTID 

⠧ Calling GitlabHTTPError: Response code 404 (Not Found)
    at onResponse (/home/hadrien_toma_1/gitlab/monorepo/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1590787476091,
    socket: 1590787476094,
    lookup: 1590787476128,
    connect: 1590787477186,
    secureConnect: 1590787477234,
    upload: 1590787477234,
    response: 1590787477467,
    end: 1590787477475,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 34,
      tcp: 1058,
      tls: 48,
      request: 0,
      firstByte: 233,
      download: 8,
      total: 1384
    }
  },
  description: undefined
}
✖ Calling Gitlab
```

Does someone have an idea about what is happening?

Context: `"@gitbeaker/cli": "^19.7.0"`

**Comment by jdalrymple** [comment]
Yup, this error makes sense, though its a bit misleading. Ill try to fix it to be clearer. Its pointing to the property mentioned in the [docs](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr), `merge_request_iid`

The code that converts the camelCase to snake_case splits on capital letters, and the original variable is called mergerequestIId. I'll change this to make sure it matches the property in the docs.
